travis:
  secure:
    BINSTAR_TOKEN: WKNrdXexP+Dd0/VQX4YeGqagse5g4Y5GITEzDKOjIbiRDkpT6wWBmH7NcoJmsKxwfaiVQB0WXAq9k6rug0RsQbG8qmpxOZiN6nJzEcspHJ1EfyiJPt0aTppWXvcJ1ssJOm3jIOxrKhUI6Soq10IN0jLZrbBp/Gf2a9GfDyeRdR7FVWe5ypVXtAwvvGu4WuQ6/t+pJKCGw441uCVrEu3FFCtQXsHeDVE9YyRo4BQodBmqUWJGZf1hfygXXhYRuy9C1MADUtkQDsPMc0UFMeEkzMgRPsEgzmt/+jyJKDc6tGJaeiLZ+yRr5vfgj1dx5Nxi9skq0+9mLiwmHLWCzHorbERJxpohQOPxo3YctfEN0JusG0biFBdozT1SLtSdkOw2bIzyqFPM/dTHcbpJerFS4mjAjIu3JJIUOcvYQfYh1CcVR667OdTHXYogv1HeFzmruFEUKZ+AlUPTi9Pec7sh0F9YHkpaGrTKQkgNF+s/cMEMnjx+3D7ucYMUYCLn98oK5+jSJfDB2+WHoOiopy/meYBjjstJa62Ka3cOXRhHmtuEnHM62WyXt6XywaFbW2d6WuXDTMIlpC2E1zCkT0JaVmNlVBZcLExW2e/r6n6Dwf7wSy1vjysYLgi6ysRnk1o8WokK40k+4SjyGuD6fMWccREgPoKCprVhOjIro4Wooi8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
